# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mojito/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter mojito sweet tucana,$(TARGET_DEVICE)),)

endif
